config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    match 'register', to: 'devise/registrations#new', via: :get
    match 'login', to: 'devise/sessions#new', via: :get
    match 'logout', to: 'devise/sessions#destroy', via: :delete

  end

  resources :todo_lists do
    resources :todo_items do
      member do
       patch :increment_priority
     end
    end
  end

  root 'todo_lists#index'

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base

	belongs_to :todo_list

	validates :content, presence: true, length: {minimum: 3}

	scope :priority, -> { order(priority: :desc)}
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base

	belongs_to :user
	has_many :todo_items, dependent: :destroy

	validates :title, presence: true, length: {minimum: 3}
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many :todo_lists
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_todo_list
  
  def new
    @todo_item = @todo_list.todo_items.new
  end

  # GET /todo_items/1/edit
  def edit
    @todo_item = @todo_list.todo_items.find(params[:id])
  end

  # POST /todo_items
  # POST /todo_items.json
  def create
    @todo_item = @todo_list.todo_items.new(todo_item_params)

    respond_to do |format|
      if @todo_item.save
        flash[:success] = 'Todo item was successfully created.'
        format.html { redirect_to root_path}
        format.json { render :show, status: :created, location: @todo_item }
      else
        flash[:error] = 'Error occured'
        format.html { redirect_to :back}
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_items/1
  # PATCH/PUT /todo_items/1.json
  def update
    @todo_item = @todo_list.todo_items.find(params[:id])
    respond_to do |format|
      if @todo_item.update(todo_item_params)
        flash[:success] = 'Todo item was successfully updated.'
        format.html { redirect_to root_path}
        format.json { render :show, status: :ok, location: @todo_item }
      else
        flash.now[:error] = 'Error occured'
        format.html { render :edit }
        format.json { render json: @todo_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_items/1
  # DELETE /todo_items/1.json
  def destroy
    @todo_item = @todo_list.todo_items.find(params[:id])
    @todo_item.destroy
    respond_to do |format|
      flash.now[:success] = 'Todo item was successfully destroyed.'
      format.html { redirect_to root_path}
      format.js   {}
      format.json { head :no_content }
    end
  end

  def increment_priority
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.update_attribute(:priority, @todo_item.priority += 1)
      flash[:success] = 'Priority changed'
      redirect_to root_url
    else
      flash[:error] = 'Something went wrong'
      redirect_to root_url
    end
  end

  private

    def set_todo_list
      @todo_list = current_user.todo_lists.find(params[:todo_list_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_item_params
      params.require(:todo_item).permit(:references, :content, :completed_at)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  
  before_action :authenticate_user!
  before_action :set_todo_list, only: [:edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = current_user.todo_lists
  end

  # GET /todo_lists/new
  def new
    @todo_list = current_user.todo_lists.new
  end

  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = current_user.todo_lists.new(todo_list_params)
    respond_to do |format|
      if @todo_list.save
        flash[:success] = 'Todo list was successfully created.'
        format.html { redirect_to root_path }
        format.json { render :show, status: :created, location: @todo_list }
      else
        flash[:error] = 'Error'
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        flash[:success] = 'Todo list was successfully updated.'
        format.html { redirect_to root_path }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        flash[:error] = 'Error'
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    flash.now[:success] = 'Todo list was successfully destroyed.'
    respond_to do |format|
      format.html { redirect_to todo_lists_url }
      format.js   { @todo_list}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = current_user.todo_lists.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params[:todo_list].permit(:title)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Garagetodo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class='container'>
	<div class= 'page-header'>
		<h1>SIMPLE TODO LISTS</h1>
		<h3>FROM RUBY GARAGE</h3>
		<% if user_signed_in? %>
			<%= link_to 'Logout', logout_path, method: :delete %>
		<%end%>
	</div><!-- end header -->
	<div class='jumbotron'>
		<main>
			<% flash.each do |key, value| %>
				<div class='alert alert-<%= key %>'>
					<%= value %>
				</div>
			<% end %>
			
			<%= yield %>
		</main>
	</div><!-- end jumbotron -->
	<footer>
		&copy; Ruby Garage
	</footer>
</div><!-- end container -->
</body>
</html>

app/views/partials/_edit_todo_item_form.html.erb
<%= form_for [@todo_list, @todo_item] do |f| %>
	<% if @todo_item.errors.any? %>
		<ul>
			<% @todo_item.errors.full_messages.each do |message|%>
				<li><%=message%></li>
			<%end%>
		</ul>
	<%end%>
	<%= f.label :content %>
	<%= f.text_field :content%>
	<%= f.submit %>
<%end%>

app/views/partials/_todo_item_form.html.erb
<%= form_for(:todo_item, url: todo_list_todo_items_path(todo_list), html:{class: 'form-inline', id: 'add_task_form'}) do |f| %>
        <%= f.text_field :content, class: 'form-control' %>
        <%= f.submit 'Add Task' %>
<%end%>

app/views/partials/_todo_list_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
  <ul>
    <% @todo_list.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
      
  <% end %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit %>
<% end %>

app/views/todo_items/destroy.js.erb
$('a[data-remote]').bind('ajax:success', function(event, data, status, xhr) {
  $(this).closest('.list-group-item').fadeOut();
});


// $( document ).ajaxSuccess(function( event, request, settings ) {
  
// });

app/views/todo_items/edit.html.erb
<h1>Edit</h1>

<%= render 'partials/edit_todo_item_form', locals: {todo_list: @todo_list, todo_item: @todo_item} %>

<%= link_to 'Back', root_path %>

app/views/todo_lists/destroy.js.erb
$('a[data-remote]').bind('ajax:success', function(event, data, status, xhr) {
  $(this).closest("#todo_list_<%= @todo_list.id %>").fadeOut();
});

app/views/todo_lists/edit.html.erb
<h1>Editing todo_list</h1>

<%= render 'partials/todo_list_form' %>

<%= link_to 'Back', root_path %>

app/views/todo_lists/index.html.erb
  <% @todo_lists.each do |todo_list| %>
    <div id="<%= dom_id(todo_list)%>">
      <div class='navbar navbar-default' role='navigation'>
        <div class='container-fluid'>
          <div class='navbar-header'>
            <div class='navbar-brand'>
              <span class='glyphicon glyphicon-list-alt'></span>
              <%= todo_list.title %>
            </div>
          </div><!--end navbar-header -->
          <div class="collapse navbar-collapse">
            <div class='nav navbar-right navbar-brand'>
              <%= link_to edit_todo_list_path(todo_list) do%>  
                <span class='glyphicon glyphicon-pencil'></span>
              <%end%>  |  
              <%= link_to todo_list, method: :delete, remote: true do%>
                <span class='glyphicon glyphicon-trash'></span>
              <%end%>
            </div><!--end nav navbar-nav navbar-right-->
          </div><!--end collapse navbar-collapse -->
        </div><!--end container -->
      </div><!--end navbar navbar-default -->
        <%= render partial: 'partials/todo_item_form', locals: {todo_list: todo_list}%>
        <div class="list-group">        
            	<% todo_list.todo_items.priority.each do |todo_item| %>
            		
                <% if todo_item.errors.any? %>
                  <ul>
                    <% @todo_item.errors.full_messages.each do |message| %>
                      <li><%= message %></li>
                    <% end %>
                  </ul>
                <% end %>

                <div class='list-group-item'>
                    <%= todo_item.content%> 
                    <div class='nav navbar-right'>
                      <%= link_to increment_priority_todo_list_todo_item_path(todo_list, todo_item), method: :patch do%>
                        <span class='glyphicon glyphicon-circle-arrow-up'></span>
                      <%end%> |                     
                      <%= link_to edit_todo_list_todo_item_path(todo_list, todo_item) do %>
                          <span class='glyphicon glyphicon-pencil'></span>
                      <%end%> |                      
                      <%= link_to todo_list_todo_item_path(todo_list, todo_item), method: :delete, remote: true, id: 'delete_item' do%>
                        <span class='glyphicon glyphicon-trash'></span>
                    </div>
                    <%end%>
                </div><!--end list-group-item-->
            	<%end%>        
        </div><!--end list-group-->
      </div><!--end dom_id -->
  <% end %>
<br>
<%= link_to 'Add TODO List', new_todo_list_path, class: 'btn btn-primary'  %>

app/views/todo_lists/new.html.erb
<h1>New Todo List</h1>

<%= render 'partials/todo_list_form' %>

<%= link_to 'Back', root_path %>